<?php

$this->headScript()->appendFile($this->basePath('js/controller/frontend/index.min.js'));

?>

<div id="calendar-toolbar" class="no-print">
    <div id="calendar-toolbar-datepicker" class="panel">
        <?= $this->partial('frontend/index/datepicker.phtml', ['dateStart' => $this->dateStart, 'dateNow' => $this->dateNow, 'squaresFilter' => $this->squaresFilter]) ?>
    </div>

<?php if ($this->user): ?>
    <div id="calendar-toolbar-doku" class="panel">
			Kurzanleitung zum Buchen: <br>
			1. Platz und Anfangszeit anklicken <br>
			2. Dauer angeben und weiterer Beschreibung folgen. 
			Siehe auch: <a href="https://www.rsk-tennis.de/docs/Dokumentation.pdf" target="_blank" >Dokumentation</a>
    </div>
<?php endif; ?>

    <div id="calendar-toolbar-userpanel" class="panel">
        <?php if ($this->user): ?>
            <?= $this->partial('frontend/index/userpanel.online.phtml', ['user' => $this->user]) ?>
        <?php else: ?>
            <?= $this->partial('frontend/index/userpanel.offline.phtml') ?>
        <?php endif; ?>
    </div>
</div>

<?= $this->calendar ?>
